"""Filings / Risk Research Agent (OpenAI Agents SDK).

Analyses a FilingEvidence bundle (bounded 10-K Risk Factors excerpts) supplied
by the caller. It has no tools and never fetches data itself. Filing provenance
(accession number, URLs, dates) is attached by code, never generated by the LLM.
"""

from __future__ import annotations

import json
import os
import re

from agents import Agent, Runner
from agents.usage import Usage
from pydantic import BaseModel, Field

from marketmind.data.filings import FilingEvidence

DEFAULT_MODEL = "gpt-4.1-mini"


class Finding(BaseModel):
    filing_statement: str = Field(description="What the filing itself says, closely paraphrased.")
    interpretation: str = Field(description="Your analytical reading of that statement, one sentence.")
    evidence_ids: list[str] = Field(description="Supporting excerpt ids, e.g. ['RF-03'].")


class EvidenceCitation(BaseModel):
    evidence_id: str
    quote: str = Field(description="Short verbatim quote (<= 30 words) copied from that excerpt.")


class FilingsAgentDraft(BaseModel):
    """Schema the LLM fills. Contains no provenance fields by design."""

    company: str
    ticker: str
    filing_summary: str = Field(description="2-3 sentences summarising the supplied risk disclosures.")
    key_risks: list[Finding] = Field(description="Max 6, most prominent risks in the evidence.")
    material_findings: list[Finding] = Field(
        description="Max 4 notable specifics (e.g. concentrations, named regions, quantified disclosures)."
    )
    evidence: list[EvidenceCitation] = Field(description="Max 8 verbatim quotes backing the findings.")
    data_limitations: list[str] = Field(description="Gaps, truncation and caveats of the evidence.")


class FilingSource(BaseModel):
    """Provenance copied from the SEC retrieval layer (not from the LLM)."""

    company_name: str | None
    cik: str | None
    form_type: str | None
    filing_date: str | None
    period_of_report: str | None
    accession_number: str | None
    filing_index_url: str | None
    primary_document_url: str | None
    sections_extracted: list[str]


class FilingsResearchOutput(FilingsAgentDraft):
    source: FilingSource


INSTRUCTIONS = """\
You are an equity research analyst reviewing SEC filing risk disclosures. You
receive JSON with:
- "filing": metadata of the filing (form, dates, accession number).
- "excerpts": verbatim excerpts from Item 1A (Risk Factors), each with an
  "evidence_id". RF-00, if present, is the company's own risk factor summary.

Grounding rules (strict):
- Use ONLY the supplied excerpts. No outside knowledge about the company, its
  products, competitors, industry, markets, news, or events after the filing.
- Every Finding must cite at least one evidence_id that exists in "excerpts".
  Never invent evidence_ids, quotes, filings, dates, page numbers or URLs.
- filing_statement = what the filing says (stay close to its wording).
  interpretation = your analytical reading, phrased with "suggests" /
  "indicates". Keep the two strictly separate.
- Quotes in "evidence" must be copied verbatim from the cited excerpt.
- Risk factor disclosures describe what COULD happen. Do not present them as
  events that have occurred unless the excerpt says so explicitly.
- Do not rank risks by likelihood or severity beyond what the text states;
  the filing notes its order is not indicative of risk level.
- Excerpts are truncated; note in data_limitations that only part of Item 1A
  was reviewed. No financial figures, valuation, price predictions or
  buy/sell/hold advice.
- Be concise: one line per field, respect the list maximums.
"""


def build_agent_input(ev: FilingEvidence) -> str:
    payload = {
        "filing": {
            "company": ev.company_name,
            "ticker": ev.ticker,
            "form_type": ev.form_type,
            "filing_date": ev.filing_date,
            "period_of_report": ev.period_of_report,
            "accession_number": ev.accession_number,
            "section": ", ".join(ev.sections_extracted),
            "risk_factor_headings_found": ev.risk_factor_count,
            "full_section_chars": ev.section_total_chars,
            "supplied_chars": ev.extracted_chars,
        },
        "excerpts": [
            {
                "evidence_id": e.evidence_id,
                "category": e.category,
                "heading": e.heading,
                "text": e.text,
                "truncated": e.truncated,
            }
            for e in ev.excerpts
        ],
        "retrieval_warnings": ev.warnings,
    }
    return json.dumps(payload, indent=1, ensure_ascii=False)


def create_filings_research_agent(model: str | None = None) -> Agent:
    return Agent(
        name="FilingsResearchAgent",
        instructions=INSTRUCTIONS,
        model=model or os.getenv("OPENAI_MODEL", DEFAULT_MODEL),
        output_type=FilingsAgentDraft,
    )


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip().lower()


def validate_output(out: FilingsAgentDraft, ev: FilingEvidence) -> list[str]:
    """Return grounding problems (empty = valid): unknown ids, non-verbatim quotes."""
    texts = {e.evidence_id: _norm(f"{e.heading or ''} {e.text}") for e in ev.excerpts}
    problems = []
    cited = {i for f in out.key_risks + out.material_findings for i in f.evidence_ids}
    cited |= {c.evidence_id for c in out.evidence}
    unknown = sorted(cited - texts.keys())
    if unknown:
        problems.append(f"unknown evidence_ids: {', '.join(unknown)}")
    for f in out.key_risks + out.material_findings:
        if not f.evidence_ids:
            problems.append(f"finding without evidence_ids: '{f.filing_statement[:60]}'")
    for c in out.evidence:
        quote = _norm(c.quote).strip(" .\"'…")
        if c.evidence_id in texts and quote not in texts[c.evidence_id]:
            problems.append(f"quote not verbatim in {c.evidence_id}: '{c.quote[:60]}'")
    return problems


def _attach_source(out: FilingsAgentDraft, ev: FilingEvidence) -> FilingsResearchOutput:
    source = FilingSource(
        company_name=ev.company_name,
        cik=ev.cik,
        form_type=ev.form_type,
        filing_date=ev.filing_date,
        period_of_report=ev.period_of_report,
        accession_number=ev.accession_number,
        filing_index_url=ev.filing_index_url,
        primary_document_url=ev.primary_document_url,
        sections_extracted=ev.sections_extracted,
    )
    # Ticker/company come from the retrieval layer, not the model.
    data = out.model_dump() | {"ticker": ev.ticker, "company": ev.company_name or out.company}
    return FilingsResearchOutput(**data, source=source)


async def run_filings_research(
    ev: FilingEvidence, model: str | None = None
) -> tuple[FilingsResearchOutput, Usage]:
    """Returns (analysis with code-attached provenance, token usage summed over all attempts).

    Validates grounding; on failure retries once with corrective feedback. If the
    retry still fails, the problems are recorded in data_limitations.
    """
    if not ev.excerpts:
        raise ValueError(f"No filing evidence for {ev.ticker}: {'; '.join(ev.warnings)}")

    agent = create_filings_research_agent(model)
    prompt = build_agent_input(ev)
    result = await Runner.run(agent, prompt)
    usage = result.context_wrapper.usage
    out = result.final_output

    problems = validate_output(out, ev)
    if problems:
        retry_prompt = (
            f"{prompt}\n\nYour previous answer had grounding problems: {'; '.join(problems)}. "
            "Rewrite the full analysis citing only existing evidence_ids and verbatim quotes."
        )
        retry = await Runner.run(agent, retry_prompt)
        usage.add(retry.context_wrapper.usage)
        out = retry.final_output
        problems = validate_output(out, ev)
        if problems:
            out.data_limitations.append(f"Validation warning: {'; '.join(problems)}.")
    return _attach_source(out, ev), usage
