"""Market / Comparable Companies Research Agent (OpenAI Agents SDK).

Analyses a WebResearchEvidence bundle (bounded Tavily excerpts) plus basic
company information supplied by the caller. It has no tools and never fetches
data itself. The agent proposes peer *names* only; tickers, listings and
financial metrics come from deterministic code (marketmind.data.peers and the
yfinance data layer). Source provenance (titles, URLs, dates) is attached by
code, never generated by the LLM. Currencies are never converted.
"""

from __future__ import annotations

import json
import os
import re
from collections.abc import Callable
from typing import Literal

from agents import Agent, Runner
from agents.usage import Usage
from pydantic import BaseModel, Field

from marketmind.data.financials import CompanyFinancials
from marketmind.data.peers import (
    PeerCandidate,
    PeerResolution,
    ResolvedPeer,
    resolve_peers,
)
from marketmind.data.web_research import WebResearchEvidence

DEFAULT_MODEL = "gpt-4.1-mini"
MIN_PEERS, MAX_PEERS = 3, 5
_SUMMARY_MAX_CHARS = 800


class PeerSelection(BaseModel):
    name: str = Field(description="Company name copied exactly as written in a cited excerpt.")
    support_type: Literal["named_competitor", "business_overlap"] = Field(
        description="named_competitor: the excerpt itself calls it a competitor/rival/peer of the "
        "target. business_overlap: the excerpt describes products/markets shared with the target."
    )
    evidence_quote: str = Field(
        description="Verbatim quote (<= 30 words) from a cited excerpt that supports support_type."
    )
    reason: str = Field(description="One sentence restating only what evidence_quote supports.")
    source_ids: list[str] = Field(description="Source ids whose excerpt names this company, e.g. ['WEB-02'].")


class ExcludedName(BaseModel):
    name: str
    reason: str = Field(description="Why it is not a genuine comparable, one short sentence.")


class SourcedStatement(BaseModel):
    statement: str = Field(description="One sentence, closely paraphrasing the cited excerpts.")
    source_ids: list[str]


class MarketAgentDraft(BaseModel):
    """Schema the LLM fills. Contains no tickers or provenance fields by design."""

    company: str
    ticker: str
    comparable_companies: list[PeerSelection] = Field(description="3-5 genuinely comparable companies.")
    considered_but_excluded: list[ExcludedName] = Field(
        description="Max 5 names in the evidence that you rejected as not genuinely comparable."
    )
    recent_company_developments: list[SourcedStatement] = Field(
        description="Max 5 developments specific to the target company."
    )
    industry_context: list[SourcedStatement] = Field(
        description="Max 4 statements on the wider industry / competitive landscape."
    )
    important_market_trends: list[SourcedStatement] = Field(
        description="Max 4 market-level trends (demand, pricing, supply)."
    )
    data_limitations: list[str] = Field(description="Gaps and caveats of the evidence.")


class WebSourceRef(BaseModel):
    """Provenance copied from the Tavily retrieval layer (not from the LLM)."""

    source_id: str
    query_purpose: str
    title: str
    url: str
    published_date: str | None


class PeerMetrics(BaseModel):
    """Provider values copied from the yfinance layer. None = not reported; never inferred."""

    current_price: float | None
    market_cap: float | None  # in `currency`
    revenue_ttm: float | None  # in `financial_currency`
    net_income_ttm: float | None  # in `financial_currency`
    trailing_pe: float | None
    forward_pe: float | None
    ev_to_ebitda: float | None
    price_to_sales: float | None


class ComparableCompany(BaseModel):
    role: str  # "target" | "peer"
    peer_name: str  # name as written in the evidence (target: yfinance name)
    ticker: str
    company_name: str | None
    exchange: str | None
    country: str | None
    currency: str | None  # trading currency: price, market cap
    financial_currency: str | None  # reporting currency: revenue, net income
    listing_basis: str | None
    # "high": agent-selected, quote-verified. "broad_peer": deterministic fallback,
    # only identified in a peers-purpose source (lower confidence). None for the target.
    peer_confidence: str | None
    source_ids: list[str]
    reason: str | None
    metrics: PeerMetrics
    missing_metrics: list[str]
    warnings: list[str]


class RejectedCandidate(BaseModel):
    name: str
    # "agent" (not comparable) | "validation" (unsupported quote) | "resolver" (listing / data)
    # | "fallback" (broad-peer fallback could not use it)
    stage: str
    source_ids: list[str]
    reason: str


class MarketResearchOutput(BaseModel):
    company: str
    ticker: str
    comparable_companies: list[PeerSelection]
    recent_company_developments: list[SourcedStatement]
    industry_context: list[SourcedStatement]
    important_market_trends: list[SourcedStatement]
    source_ids_used: list[str]
    sources: list[WebSourceRef]
    comps_dataset: list[ComparableCompany]
    rejected_peers: list[RejectedCandidate]
    data_limitations: list[str]
    warnings: list[str]


INSTRUCTIONS = """\
You are an equity research analyst identifying comparable companies and market
context. You receive JSON with:
- "company": basic provider information about the target (name, ticker,
  sector, industry, business summary).
- "sources": web search excerpts, each with a "source_id" and a
  "query_purpose" ("peers", "company_news" or "industry_news").

Grounding rules (strict):
- Use ONLY the supplied company information and source excerpts. No outside
  knowledge of competitors, products, market shares, news or events.
- Cite only source_ids that exist in "sources". Never invent source ids,
  URLs, dates, figures or company names. Every statement cites at least one id.
- Do NOT output ticker symbols anywhere. Tickers are resolved later by code.

Comparable companies:
- Select 3-5 companies that a cited excerpt names explicitly AND for which the
  cited excerpt text itself supports comparability in one of two ways:
  * named_competitor: the excerpt describes the company as a competitor,
    rival or peer of the target (e.g. "its main competitors are X and Y").
  * business_overlap: the excerpt contains wording showing the company makes
    the same kind of products or serves the same end markets as the target.
- A name that only appears in a generic list, ticker table, ratio table or
  page titled "competitors"/"peers", with at most a broad sector label (e.g.
  "Semiconductors", "Computer Hardware"), does NOT qualify. Exclude it and
  list it in considered_but_excluded. Never use your own knowledge of what a
  company does to fill the gap. Never select the target itself.
- evidence_quote must be copied verbatim from the excerpt text of a cited
  source and contain the supporting wording; for named_competitor it must
  also contain the peer's name and the competitor/rival/peer wording.
- If fewer than 3 companies qualify, select only those that do and say so in
  data_limitations. Never pad the list with unsupported names.
- "name" must be copied exactly as it is written in the cited excerpt (e.g. if
  the excerpt says "SK Hynix", write "SK Hynix"), so code can verify it. Cite
  only source_ids whose excerpt actually contains that name.
- "reason" restates only what evidence_quote supports. Do not add business
  descriptions, market shares or rankings that the quote does not contain.
- List notable names you rejected (e.g. broad semiconductor or hardware names)
  in considered_but_excluded with a short reason.

Developments and context:
- recent_company_developments: events specific to the target company only.
- industry_context: the competitive landscape / industry structure.
- important_market_trends: market-level demand, pricing and supply trends.
  Keep company-specific news out of the industry lists and vice versa.
- Excerpts are short snippets and may be dated or promotional; state facts as
  reported by the source ("reported", "according to"), not as verified truth.
  No valuation judgements, price predictions or buy/sell/hold advice.
- data_limitations: note thin, undated or one-sided evidence.
- Be concise: one line per item, respect the list maximums.
"""


def build_agent_input(ev: WebResearchEvidence, fin: CompanyFinancials) -> str:
    summary = (fin.business_summary or "")[:_SUMMARY_MAX_CHARS] or None
    payload = {
        "company": {
            "name": fin.company_name or ev.company_name,
            "ticker": ev.ticker,
            "sector": fin.sector,
            "industry": fin.industry,
            "business_summary": summary,
        },
        "sources": [
            {
                "source_id": s.source_id,
                "query_purpose": s.query_purpose,
                "title": s.title,
                "published_date": s.published_date,
                "excerpt": s.excerpt,
            }
            for s in ev.sources
        ],
        "retrieval_warnings": ev.warnings,
    }
    return json.dumps(payload, indent=1, ensure_ascii=False)


def create_market_research_agent(model: str | None = None) -> Agent:
    return Agent(
        name="MarketResearchAgent",
        instructions=INSTRUCTIONS,
        model=model or os.getenv("OPENAI_MODEL", DEFAULT_MODEL),
        output_type=MarketAgentDraft,
    )


def _statements(out: MarketAgentDraft) -> list[SourcedStatement]:
    return out.recent_company_developments + out.industry_context + out.important_market_trends


def _cited_ids(out: MarketAgentDraft) -> set[str]:
    ids = {i for p in out.comparable_companies for i in p.source_ids}
    return ids | {i for s in _statements(out) for i in s.source_ids}


_COMPETITOR_RE = re.compile(r"compet|rival|\bpeers?\b", re.IGNORECASE)


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip().lower()


def peer_support_problem(p: PeerSelection, ev: WebResearchEvidence) -> str | None:
    """Why a peer's evidence_quote does not support its selection (None = supported)."""
    excerpts = {s.source_id: _norm(s.excerpt) for s in ev.sources}
    quote = _norm(p.evidence_quote).strip(" .\"'…")
    if not quote:
        return f"peer '{p.name}' has no evidence_quote"
    if not any(quote in excerpts.get(sid, "") for sid in p.source_ids):
        return f"evidence_quote for '{p.name}' is not verbatim in its cited excerpts"
    if p.support_type == "named_competitor":
        if _norm(p.name) not in quote:
            return f"named_competitor quote for '{p.name}' does not contain the peer name"
        if not _COMPETITOR_RE.search(quote):
            return f"named_competitor quote for '{p.name}' has no competitor/rival/peer wording"
    return None


def validate_output(out: MarketAgentDraft, ev: WebResearchEvidence) -> list[str]:
    """Return hard grounding problems (empty = valid).

    Each peer's evidence_quote must be verbatim in a cited excerpt (and, for
    named_competitor, contain the name and competitor wording). Name-in-excerpt
    verification and listing checks happen later in the resolver.
    """
    known = {s.source_id for s in ev.sources}
    problems = []
    unknown = sorted(_cited_ids(out) - known)
    if unknown:
        problems.append(f"unknown source ids: {', '.join(unknown)}")
    for p in out.comparable_companies:
        if not p.source_ids:
            problems.append(f"peer without source_ids: '{p.name}'")
        elif problem := peer_support_problem(p, ev):
            problems.append(problem)
    for s in _statements(out):
        if not s.source_ids:
            problems.append(f"statement without source_ids: '{s.statement[:60]}'")
    # Fewer than MIN_PEERS is allowed (never pad); the resolver warns about it.
    if len(out.comparable_companies) > MAX_PEERS:
        problems.append(f"{len(out.comparable_companies)} peers selected (max {MAX_PEERS})")
    return problems


def _metrics(fin: CompanyFinancials | None) -> tuple[PeerMetrics, list[str]]:
    v = fin.valuation if fin else {}
    m = PeerMetrics(
        current_price=fin.current_price if fin else None,
        market_cap=fin.market_cap if fin else None,
        revenue_ttm=fin.revenue if fin else None,
        net_income_ttm=fin.net_income if fin else None,
        trailing_pe=v.get("trailing_pe"),
        forward_pe=v.get("forward_pe"),
        ev_to_ebitda=v.get("enterprise_to_ebitda"),
        price_to_sales=v.get("price_to_sales"),
    )
    return m, [k for k, val in m.model_dump().items() if val is None]


def _currency_warnings(fin: CompanyFinancials | None) -> list[str]:
    if fin and fin.currency and fin.financial_currency and fin.currency != fin.financial_currency:
        return [
            f"Trading currency {fin.currency} differs from reporting currency "
            f"{fin.financial_currency}; provider ratios may mix currencies."
        ]
    return []


def build_comps_dataset(
    target: CompanyFinancials,
    draft: MarketAgentDraft,
    resolution: PeerResolution,
    broad_reasons: dict[str, str] | None = None,
) -> list[ComparableCompany]:
    """Target row + one row per resolved peer, values copied as reported (no conversion)."""
    broad_reasons = broad_reasons or {}
    reasons = {p.name: p.reason for p in draft.comparable_companies} | broad_reasons
    tm, tmissing = _metrics(target)
    rows = [
        ComparableCompany(
            role="target",
            peer_name=target.company_name or target.ticker,
            ticker=target.ticker,
            company_name=target.company_name,
            exchange=None,
            country=None,
            currency=target.currency,
            financial_currency=target.financial_currency,
            listing_basis=None,
            peer_confidence=None,
            source_ids=[],
            reason=None,
            metrics=tm,
            missing_metrics=tmissing,
            warnings=_currency_warnings(target),
        )
    ]
    for p in resolution.peers:
        m, missing = _metrics(p.financials)
        rows.append(
            ComparableCompany(
                role="peer",
                peer_name=p.peer_name,
                ticker=p.ticker,
                company_name=p.company_name,
                exchange=p.exchange,
                country=p.country,
                currency=p.currency,
                financial_currency=p.financials.financial_currency if p.financials else None,
                listing_basis=p.listing_basis,
                peer_confidence="broad_peer" if p.peer_name in broad_reasons else "high",
                source_ids=p.source_ids,
                reason=reasons.get(p.peer_name),
                metrics=m,
                missing_metrics=missing,
                warnings=_currency_warnings(p.financials),
            )
        )
    return rows


def _peer_warnings(peers: list[ResolvedPeer]) -> list[str]:
    """Same peer-count / currency warnings as the resolver, recomputed after the fallback."""
    warnings = []
    if len(peers) < MIN_PEERS:
        warnings.append(f"Only {len(peers)} valid peers resolved (target is {MIN_PEERS}-{MAX_PEERS}).")
    currencies = sorted({p.currency for p in peers if p.currency})
    if len(currencies) > 1:
        warnings.append(
            f"Peers report in multiple currencies ({', '.join(currencies)}); "
            "values are not converted, so absolute figures are not directly comparable."
        )
    return warnings


def broad_peer_fallback(
    names: list[str],
    ev: WebResearchEvidence,
    target: CompanyFinancials,
    resolution: PeerResolution,
) -> tuple[dict[str, str], list[RejectedCandidate]]:
    """Top up `resolution.peers` to MIN_PEERS with lower-confidence broad peers (in place).

    Deterministic: candidate names (already mentioned by the agent) must appear
    in the excerpt text (not just the title) of a source retrieved for the
    "peers" purpose, and are
    resolved one at a time through the existing yfinance resolver. Names found in
    more peer sources are tried first. The reason is a fixed provenance statement,
    never a business-overlap claim. Returns (name -> reason, fallback rejections).
    """
    peer_excerpts = {s.source_id: _norm(s.excerpt) for s in ev.sources if s.query_purpose == "peers"}
    have = {_norm(p.peer_name) for p in resolution.peers}
    seen_tickers = {ev.ticker} | {p.ticker for p in resolution.peers}
    reasons: dict[str, str] = {}
    rejected: list[RejectedCandidate] = []

    ranked, seen_names = [], set(have)
    for name in names:
        if _norm(name) in seen_names:
            continue
        seen_names.add(_norm(name))
        ids = [sid for sid, text in peer_excerpts.items() if _norm(name) in text]
        if ids:
            ranked.append((name, ids))
        else:
            rejected.append(RejectedCandidate(
                name=name, stage="fallback", source_ids=[],
                reason="not found in any peers-purpose source excerpt",
            ))
    ranked.sort(key=lambda c: -len(c[1]))  # stable: ties keep the agent's order

    for name, ids in ranked:
        if len(resolution.peers) >= MIN_PEERS:
            break
        res = resolve_peers(ev.ticker, [PeerCandidate(name, ids)], ev.sources,
                            target.company_name, max_peers=1)
        if not res.peers:
            reason = res.rejected[0].reason if res.rejected else "not resolved"
            rejected.append(RejectedCandidate(name=name, stage="fallback", source_ids=ids, reason=reason))
            continue
        peer = res.peers[0]
        if peer.ticker in seen_tickers:
            rejected.append(RejectedCandidate(
                name=name, stage="fallback", source_ids=ids,
                reason=f"resolves to {peer.ticker}, already included or the target",
            ))
            continue
        seen_tickers.add(peer.ticker)
        resolution.peers.append(peer)
        reasons[name] = (
            f"Broad peer (lower confidence): identified in peer/competitor source(s) "
            f"{', '.join(peer.source_ids)}; the evidence does not describe specific business overlap."
        )
    resolution.warnings = [
        w for w in resolution.warnings if not w.startswith(("Only ", "Peers report in multiple"))
    ] + _peer_warnings(resolution.peers)
    return reasons, rejected


def _assemble(
    draft: MarketAgentDraft,
    ev: WebResearchEvidence,
    target: CompanyFinancials,
    resolution: PeerResolution,
    broad_reasons: dict[str, str] | None = None,
) -> MarketResearchOutput:
    broad_reasons = broad_reasons or {}
    # Broad peers keep no agent-written reason, even if the agent proposed them.
    resolved = {p.peer_name for p in resolution.peers} - broad_reasons.keys()
    used = sorted(_cited_ids(draft) & {s.source_id for s in ev.sources})
    rejected = [
        RejectedCandidate(name=x.name, stage="agent", source_ids=[], reason=x.reason)
        for x in draft.considered_but_excluded
        if x.name not in broad_reasons
    ] + [
        RejectedCandidate(name=r.peer_name, stage="resolver", source_ids=r.source_ids, reason=r.reason)
        for r in resolution.rejected
        if r.peer_name not in broad_reasons
    ]
    return MarketResearchOutput(
        # Ticker/company come from the retrieval layer, not the model.
        company=target.company_name or ev.company_name or draft.company,
        ticker=ev.ticker,
        comparable_companies=[p for p in draft.comparable_companies if p.name in resolved],
        recent_company_developments=draft.recent_company_developments,
        industry_context=draft.industry_context,
        important_market_trends=draft.important_market_trends,
        source_ids_used=used,
        sources=[
            WebSourceRef(
                source_id=s.source_id,
                query_purpose=s.query_purpose,
                title=s.title,
                url=s.url,
                published_date=s.published_date,
            )
            for s in ev.sources
            if s.source_id in used
        ],
        comps_dataset=build_comps_dataset(target, draft, resolution, broad_reasons),
        rejected_peers=rejected,
        data_limitations=draft.data_limitations,
        warnings=ev.warnings + resolution.warnings,
    )


async def run_market_research(
    ev: WebResearchEvidence,
    target: CompanyFinancials,
    model: str | None = None,
    on_retry: Callable[[str], None] | None = None,
) -> tuple[MarketResearchOutput, Usage]:
    """Returns (analysis + deterministic comps dataset, token usage summed over all attempts).

    Validates grounding; on failure retries once with corrective feedback. If the
    retry still fails, the problems are recorded in data_limitations. Peer names
    are then verified, resolved to listings and enriched by code. If fewer than
    MIN_PEERS survive, broad_peer_fallback tops up with lower-confidence peers.
    `on_retry(reason)` is called when the corrective retry is triggered.
    """
    if not ev.sources:
        raise ValueError(f"No web evidence for {ev.ticker}: {'; '.join(ev.warnings)}")

    agent = create_market_research_agent(model)
    prompt = build_agent_input(ev, target)
    result = await Runner.run(agent, prompt)
    usage = result.context_wrapper.usage
    draft = result.final_output

    problems = validate_output(draft, ev)
    if problems:
        if on_retry:
            on_retry("; ".join(problems))
        retry_prompt = (
            f"{prompt}\n\nYour previous answer had grounding problems: {'; '.join(problems)}. "
            "Rewrite the full analysis citing only existing source_ids. Keep only peers whose "
            "evidence_quote is verbatim and supports them; drop the rest rather than padding."
        )
        retry = await Runner.run(agent, retry_prompt)
        usage.add(retry.context_wrapper.usage)
        draft = retry.final_output
        problems = validate_output(draft, ev)
        if problems:
            draft.data_limitations.append(f"Validation warning: {'; '.join(problems)}.")

    unsupported = {}
    for p in draft.comparable_companies:
        if problem := peer_support_problem(p, ev):
            unsupported[p.name] = problem
    supported = [p for p in draft.comparable_companies if p.name not in unsupported]
    candidates = [PeerCandidate(p.name, p.source_ids) for p in supported]
    resolution = resolve_peers(
        ev.ticker, candidates, ev.sources, target.company_name, max_peers=MAX_PEERS
    )
    broad_reasons: dict[str, str] = {}
    fallback_rejected: list[RejectedCandidate] = []
    if len(resolution.peers) < MIN_PEERS:
        names = [p.name for p in draft.comparable_companies if p.name in unsupported]
        names += [x.name for x in draft.considered_but_excluded]
        names += [r.peer_name for r in resolution.rejected]
        broad_reasons, fallback_rejected = broad_peer_fallback(names, ev, target, resolution)

    out = _assemble(draft, ev, target, resolution, broad_reasons)
    out.rejected_peers += [
        RejectedCandidate(
            name=p.name, stage="validation", source_ids=p.source_ids, reason=unsupported[p.name]
        )
        for p in draft.comparable_companies
        if p.name in unsupported and p.name not in broad_reasons
    ] + fallback_rejected
    return out, usage
